# This workflow will build an angular project
# For more information see: 

on:
  workflow_call:
    inputs:
      TESTCOVERAGE_THRESHOLD:
        type: number
        required: false
        default: 90
      NODE_VERSION:
        type: string
        required: false
        default: '16'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node $
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test:headless

      - name: build
        run: npm run build:prod

