# This workflow will build an angular project
# For more information see: 

on:
  workflow_call:
    inputs:
      TESTCOVERAGE_THRESHOLD:
        type: number
        required: false
        default: 90
      NODE_VERSION:
        type: string
        required: false
        default: '16'

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm test

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Zip output
      run: zip -qq -r function.zip dist node_modules package.json
      working-directory: path/to/work-dir

